### ISSUE TITLE
i want to know the huggingface_hub 's version ,because sth had wrong.

### ISSUE THREAD

**Issue by Sillyyk** [hmchuong/MaGGIe#1]

**Comment by hmchuong** [comment]
What is the error?

**Comment by Sillyyk** [comment]
> What is the error?

感谢您的回复，退了版本后只是网络问题了
An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

加入os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"能解决了

**Comment by Sillyyk** [comment]
> What is the error?

I still want to know why the mask and mate that put in the video output of two people are both from the same person

**Comment by hmchuong** [comment]
> > What is the error?
> 
> 感谢您的回复，退了版本后只是网络问题了 An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
> 
> 加入os.environ["HF_ENDPOINT"] = "[https://hf-mirror.com"能解决了](https://hf-mirror.com%22%E8%83%BD%E8%A7%A3%E5%86%B3%E4%BA%86)

I'm not sure, maybe you cannot connect to the Huggingface

**Comment by hmchuong** [comment]
> > What is the error?
> 
> I still want to know why the mask and mate that put in the video output of two people are both from the same person

I am not sure I understand your concern

**Comment by Sillyyk** [comment]
> > > What is the error?
> > 
> > 
> > I still want to know why the mask and mate that put in the video output of two people are both from the same person
> 
> I am not sure I understand your concern

Your work is amazing,but what I want to know is how to make the output make all the characters alpha matting instead of one after another.

**Comment by hmchuong** [comment]
> > > > What is the error?
> > > 
> > > 
> > > I still want to know why the mask and mate that put in the video output of two people are both from the same person
> > 
> > 
> > I am not sure I understand your concern
> 
> Your work is amazing,but what I want to know is how to make the output make all the characters alpha matting instead of one after another.

Do you mean the alpha matte of all instances as a single alpha matte? If yes, you can sum all alpha matte together.
