### ISSUE TITLE
Loading from huggingface

### ISSUE THREAD

**Issue by Junoh-Kang** [hmchuong/MaGGIe#3]
Dear authors,

I tried to run video evaluation, but it did not work because there were some problems with loading weights. It seems the problem is caused since `is_from_hf` is set to `False` even I used the checkpoint from hugging face. The hugging face checkpoint is directory, not a file, so I changed `if cfg.weights != '' and not os.path.exists(cfg.weights):` ( 7th row of `maggie/network/__init__.py`) to `if cfg.weights != '' and not os.path.isfile(cfg.weights):` and it finally works!

Best, Junoh

**Comment by hmchuong** [comment]
Thank you, I've updated the model based on
