### ISSUE TITLE
Curious About how weights are loading.

### ISSUE THREAD

**Issue by UsamaHasan** [hmchuong/MaGGIe#4]
Hy, First of all, thanks for making your code public and this great effort. I'm getting this error on line 10, I'm not sure why this is happening, but 
`eval(cfg.arch).from_pretrained(cfg.weights)` 
due to this model doesn't get initialized. 
`model, is_from_hf = build_model(cfg.model)
  File "/data/usama/MaGGIe/tools/../maggie/network/__init__.py", line 19, in build_model
    return model, is_from_hf
UnboundLocalError: local variable 'model' referenced before assignment`

Fromt what I'm aware of huggingface should automatically download the weights file, but I have the way as well and downloaded the folder. Can you please help me which this.

**Comment by hmchuong** [comment]
Could you remove try/except block and update your config weights with your local path and try again?
