### ISSUE TITLE
pretrained model shape don’t match with model definition

### ISSUE THREAD

**Issue by josh-zhu** [hmchuong/MaGGIe#6]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MaGGIe_Temp:
	size mismatch for decoder.dummy_downscale.0.weight: copying a param with shape torch.Size([32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 3]).
	size mismatch for decoder.dummy_downscale.1.weight: copying a param with shape torch.Size([32, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 32]).
	size mismatch for decoder.dummy_downscale.2.weight: copying a param with shape torch.Size([64, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 64, 32]).
	size mismatch for decoder.dummy_downscale.3.weight: copying a param with shape torch.Size([64, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 64, 64]).
	size mismatch for decoder.layer3.0.weight: copying a param with shape torch.Size([64, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 64, 64]).
	size mismatch for decoder.layer3.3.weight: copying a param with shape torch.Size([64, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 64, 64]).
	size mismatch for decoder.guidance_layer.0.weight: copying a param with shape torch.Size([64, 1, 1, 128]) from checkpoint, the shape in current model is torch.Size([1, 1, 64, 128]).
	size mismatch for decoder.guidance_layer.3.weight: copying a param with shape torch.Size([64, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 64, 64]).
	size mismatch for decoder.layer3_smooth.0.weight: copying a param with shape torch.Size([64, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 64, 64]).
	size mismatch for decoder.layer4.0.weight: copying a param with shape torch.Size([32, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 64]).
	size mismatch for decoder.layer4.3.weight: copying a param with shape torch.Size([32, 1, 1, 32]) from checkpoint, the shape in current model is torch.Size([1, 1, 32, 32]).
	size mismatch for decoder.layer4_smooth.0.weight: copying a param with shape torch.Size([32, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 32, 64]).
	size mismatch for decoder.layer5.0.weight: copying a param with shape torch.Size([32, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 32]).
	size mismatch for decoder.layer5.3.weight: copying a param with shape torch.Size([32, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 32]).
	size mismatch for decoder.layer5_smooth.0.weight: copying a param with shape torch.Size([32, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 32, 64]).
	size mismatch for decoder.refine_OS4.0.weight: copying a param with shape torch.Size([32, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 64]).
	size mismatch for decoder.refine_OS4.3.weight: copying a param with shape torch.Size([1, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 1, 32]).
	size mismatch for decoder.refine_OS1.0.weight: copying a param with shape torch.Size([32, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 32, 32]).
	size mismatch for decoder.refine_OS1.3.weight: copying a param with shape torch.Size([1, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 1, 32]).

**Comment by hmchuong** [comment]
can you share the configs you used?

**Comment by hmchuong** [comment]
closed as no response
